name: Build a JAR in Spring Boot using Spring Boot

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'

      - name: Build with Maven
        run: mvn clean install

      - name: Run Tests
        run: mvn test

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: target/test-classes

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'

      - name: Archive Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-reports
          path: target/surefire-reports
